apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: microservices-demo-app
build:
  artifacts:
  - image: accountservice
    context: src/account-service    
  - image: balancesheet
    context: src/balance-sheet-service
  - image: frontend
    context: src/frontend    
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
