apiVersion: skaffold/v2beta3
kind: Config
metadata:
  name: microservices-demo-app
build:
  artifacts:
  - image: accountservice
    context: src/account-service  
  - image: balancesheet
    context: src/balance-sheet-service
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/account-service-db.yaml
    - kubernetes-manifests/account-service.yaml
    - kubernetes-manifests/balance-sheet.yaml
    - kubernetes-manifests/balance-sheet-db.yaml
    - kubernetes-manifests/redis.yaml
    - kubernetes-manifests/rabbit-mq.yaml
