spring:
  datasource:
    url: jdbc:postgresql://account-service-db.default.svc.cluster.local/account
    username: account
    password: account

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'