spring:
  datasource:
    url: jdbc:postgresql://account-service-db/account
    username: account
    password: account

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbit-service


queue:
  user:
    name: new-user-queue